name: Deploy Flask App to Debian Server

on:
  push:
    branches:
      - main  # DÃ©clenche le workflow sur chaque push dans la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH Setup & Deployment
        shell: bash
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATA_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H kascali.de >> ~/.ssh/known_hosts

          # Deploy to server
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@kascali.de << 'EOF'
            echo "ðŸ”§ Switching to app directory"
            cd /var/www/Example-CI-CD-Github-Action || exit 1

            # Add the directory as a safe directory
            git config --global --add safe.directory /var/www/Example-CI-CD-Github-Action

            echo "ðŸ”„ Pulling latest code"
            git pull origin main || exit 1

            echo "ðŸ Activating virtual environment"
            source env/bin/activate || exit 1

            echo "ðŸ“¦ Installing dependencies"
            pip install -r requirements.txt || exit 1

            echo "ðŸš€ Restarting service"
            sudo systemctl restart Example-CI-CD-Github-Action || exit 1
          EOF
