name: Deploy Flask App via Docker

on:
  push:
    branches:
      - main  #

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_HUB_USER }}/kwelin_childrens_hospital:latest
          echo " Building Docker image $IMAGE_NAME"
          docker build -t $IMAGE_NAME .
          echo " Pushing Docker image to Docker Hub"
          docker push $IMAGE_NAME


      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATA_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_HUB_USER }}/kwelin_childrens_hospital:latest
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
            echo "ðŸ”§ Pulling latest Docker image $IMAGE_NAME"
            docker pull $IMAGE_NAME || exit 1
            echo "ðŸ›‘ Stopping old container"
            docker stop kwelin_childrens_hospital || true
            docker rm kwelin_childrens_hospital || true
            echo "â–¶ï¸ Starting new container on port 5203"
            docker run -d --name kwelin_childrens_hospital -p 5203:5000 $IMAGE_NAME || exit 1
          EOF
    

